export const allRequests = [
  {   request_id: '#req-000001',
      employee_name: 'Ibrahim Benzineb',
      article_name: 'منحة الوفاة',
      chapter_name: 'المساعدات الاجتماعية',
      amount: '10,000 DZD',
      payment_methode: 'Payment par virement',
      request_status: 'Rejected'
    },
    {   request_id: '#req-000002',
    employee_name: 'Ibrahim Benzineb',
    article_name: 'منحة الوفاة',
    chapter_name: 'المساعدات الاجتماعية',
    amount: '10,000 DZD',
    payment_methode: 'Payment par virement',
    request_status: 'Pending'
  },
  {   request_id: '#req-000003',
  employee_name: 'Ibrahim Benzineb',
  article_name: 'منحة الوفاة',
  chapter_name: 'المساعدات الاجتماعية',
  amount: '10,000 DZD',
  payment_methode: 'Payment par virement',
  request_status: 'Pending'
},
{   request_id: '#req-000004',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Pending'
},
{   request_id: '#req-000005',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Pending'
},
{   request_id: '#req-000006',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Pending'
},
{   request_id: '#req-000007',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000008',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000009',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000010',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000011',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000012',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000013',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000014',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
{   request_id: '#req-000015',
employee_name: 'Ibrahim Benzineb',
article_name: 'منحة الوفاة',
chapter_name: 'المساعدات الاجتماعية',
amount: '10,000 DZD',
payment_methode: 'Payment par virement',
request_status: 'Paid'
},
    
];